apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes: 
        - name: image
          emptyDir: {}
      containers:
        - name: project-backend
          image: ankaleh/project-backend:v1.1
          volumeMounts:
          - name: image
            mountPath: /usr/src/app/files
