apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: kub-project
spec:
  type: ClusterIP
  selector:
    app: project-backend # This is the app as declared in the deployment.
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 4000
      name: http