apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: pongs
          emptyDir: {}
      containers:
        - name: ping-pong
          image: ankaleh/ping-pong:v1.6
          env:
            - name: USER # ENV name passed to container
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER # ENV name in the secret
            - name: PASSWORD # ENV name passed to container
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD # ENV name in the secret
          volumeMounts:
          - name: pongs
            mountPath: /usr/src/app/files
