apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: pongs
          emptyDir: {}
      containers:
        - name: ping-pong
          image: ankaleh/ping-pong:v0.4
          volumeMounts:
          - name: pongs
            mountPath: /usr/src/app/files
