apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-project
  template:
    metadata:
      labels:
        app: kub-project
    spec:
      volumes:
        - name: image
          emptyDir: {}
      containers:
        - name: kub-project
          image: ankaleh/kub-project:v0.7.3
          volumeMounts:
          - name: image
            mountPath: /usr/src/app/files
