apiVersion: v1
kind: Service
metadata:
  name: kub-project-svc
spec:
  type: ClusterIP
  selector:
    app: kub-project # This is the app as declared in the deployment.
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 3000