apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - image: postgres
    imagePullPolicy: IfNotPresent
    name: postgres
    ports:
    - containerPort: 5432 #postgres default port is 5432
    env:
      - name: POSTGRES_USER # ENV name passed to container (here from postgres image documentation in Dockerhub)
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: USER # ENV name in the secret
      - name: POSTGRES_PASSWORD # ENV name passed to container
        valueFrom:
          secretKeyRef:
              name: db-secrets
              key: PASSWORD # ENV name in the secret