apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER # ENV name passed to container (here from postgres image documentation in Dockerhub)
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER # ENV name in the secret
            - name: POSTGRES_PASSWORD # ENV name passed to container
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD # ENV name in the secret
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: dbdata
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi